env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - standard
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  'indent': 'off',
  '@typescript-eslint/indent': ['error', 2],
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': 'error',
}
